type_checks:
  character:
    - identifier
    - rate_id
  numeric:
    - line_no
    - actual_rate
    - pro_rata_rate
    - check
    - residential_rate
    - pce_eligible_residential_k_wh
    - pce_eligible_com_facil_k_wh
    - pce_eligible_community_k_wh
    - pce_eligible_k_wh_total
  logical:


constraints:
  not_null:
    - identifier
    - line_no
  positive_only:
    - actual_rate
    - residential_rate
  detect_outliers:
