# This config file contains column renames for individual sheets in the source XLSX files

# SheetName:
#   Old Column Name: "new_column_name"

HeaderData:
  Identifier: "identifier"
  Line No: "line_no"
  Utility: "utility"
  Community: "community"
  Amount: "amount"
  Purchased From: "purchased_from"
  Powerhouse Consumption k Wh: "powerhouse_consumption_kwh"
  Peak Consumption k W: "peak_consumption_kw"
  Residential Sold To: "residential_sold_to"
  Commercial Sold To: "commercial_sold_to"
  Com Facil Sold To: "com_facil_sold_to"
  Govt Facil Sold To: "govt_facil_sold_to"
  Unbilled Sold To: "unbilled_sold_to"
  Most Recent Fuel Purch Price: "most_recent_fuel_purch_price"
  Fuel Used Gallons: "fuel_used_gallons"
  Non Fuel Expenses: "non_fuel_expenses"
  Fuel Cost: "fuel_cost"
  Total k Wh Purchased: "total_kwh_purchased"
  Residential Customers: "residential_customers"
  Commercial Customers: "commercial_customers"
  Com Facil Customers: "com_facil_customers"
  Govt Facil Customers: "govt_facil_customers"
  Unbilled Customers: "unbilled_customers"
  Other Customers: "other_customers"
  Other Customers Description: "other_customers_description"
  Diesel k Wh Generated: "diesel_kwh_generated"
  Hydro k Wh Generated: "hydro_kwh_generated"
  Other 1 k Wh Type: "other_1_kwh_type"
  Other 1 k Wh Generated: "other_1_kwh_generated"
  Other 2 k Wh Type: "other_2_kwh_type"
  Other 2 k Wh Generated: "other_2_kwh_generated"
  UMR Month: "umr_month"
  Fiscal Year: "fiscal_year"
  Calendar Year: "calendar_year"

RateLineData:
  Identifier: "identifier"
  Line No: "line_no"
  Actual Rate: "actual_rate"
  Pro Rata Rate: "pro_rata_rate"
  Check: "check"
  Residential Rate: "residential_rate"
  PCE Eligible Residential k Wh: "pce_eligible_residential_kwh"
  PCE Eligible Com Facil k Wh: "pce_eligible_com_facil_kwh"
  PCE Eligible Community k Wh: "pce_eligible_community_kwh"
  PCE Eligible k Wh Total: "pce_eligible_kwh_total"
  Rate ID: "rate_id"
